# Generated by Django 5.1.2 on 2024-10-30 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_post_author_news_post_author2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_post',
            old_name='author2',
            new_name='author',
        ),
        migrations.AddField(
            model_name='news_post',
            name='author2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='news_post',
            name='id_author2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author2', to=settings.AUTH_USER_MODEL),
        ),
    ]
