# Generated by Django 5.1.2 on 2024-10-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_post',
        ),
    ]
